### PR TITLE
Fix help with line breaks

### LINKED ISSUE #239: Error executing the task when the documentation has multiple lines
## Description of the bug

When I create a task that has its documentation (**help**) with more than one line, no error is displayed when listing the tasks configured with the `poe --help` command, but when executing this task an error appears, preventing your concussion.

### Error displayed

``` shell
Error: Invalid task 'fmt'
	 | Help messages must not contain line breaks
```

### Dependencies

The following versions were used for testing:

| dependency | version                              |
|------------|--------------------------------------|
| python     | **3.12.5**                           |
| poetry     | **1.8.3**                            |
| poethepoet | **0.26.1** - **0.27.0** - **0.28.0** |

<details>
<summary>
	<b>pyproject.toml</b> file with the  <b>fmt </b> task that has documentation with more than one line
</summary>

``` toml
[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "3.12.5"
poethepoet = "^0.28.0"
black = "^24.8.0"

[tool.poe.tasks.fmt]
help = """\n
	 Use "poe fmt" to format the code.

	 Examples:
	   # Format all files
	   poe fmt
"""
cmd = "black -S -l 79 $PATH"
[tool.poe.tasks.fmt.args.PATH]
options = ["-p", "--path"]
default = "."
help = """\n
	 Change the path that will be formatted.

	 Examples:
	   # Formatting a specific path
	   poe fmt -p tests
"""

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

</details>

### Steps

1. Install project dependencies:

``` shell
poetry install
```

2. List the successfully configured tasks:

``` shell
poetry run poe --help
```

<details>
<summary>
	Full output of <b>poetry run poe --help</b> command
</summary>

``` shell
Poe the Poet - A task runner that works well with poetry.
version 0.28.0

Usage:
  poe [global options] task [task arguments]

Global options:
  -h, --help            Show this help page and exit
  --version             Print the version and exit
  -v, --verbose         Increase command output (repeatable)
  -q, --quiet           Decrease command output (repeatable)
  -d, --dry-run         Print the task contents but don't actually run it
  -C PATH, --directory PATH
						Specify where to find the pyproject.toml
  -e EXECUTOR, --executor EXECUTOR
						Override the default task executor
  --ansi                Force enable ANSI output
  --no-ansi             Force disable ANSI output

Configured tasks:
  fmt

	 Use "poe fmt" to format the code.

	 Examples:
	   # Format all files
	   poe fmt

	-p, --path

	 Change the path that will be formatted.

	 Examples:
	   # Formatting a specific path
	   poe fmt -p tests
 [default: .]
```

</details>

3. Running task with error:

``` shell
poetry run poe fmt
```

<details>
	<summary>
		Full error output from <b>poe fmt</b> command
	</summary>

``` shell
Poe the Poet - A task runner that works well with poetry.
version 0.28.0

Error: Invalid task 'fmt'
	 | Help messages must not contain line breaks

Usage:
  poe [global options] task [task arguments]

Global options:
  -h, --help            Show this help page and exit
  --version             Print the version and exit
  -v, --verbose         Increase command output (repeatable)
  -q, --quiet           Decrease command output (repeatable)
  -d, --dry-run         Print the task contents but don't actually run it
  -C PATH, --directory PATH
						Specify where to find the pyproject.toml
  -e EXECUTOR, --executor EXECUTOR
						Override the default task executor
  --ansi                Force enable ANSI output
  --no-ansi             Force disable ANSI output

Configured tasks:
  fmt

	 Use "poe fmt" to format the code.

	 Examples:
	   # Format all files
	   poe fmt

	-p, --path

	 Change the path that will be formatted.

	 Examples:
	   # Formatting a specific path
	   poe fmt -p tests
 [default: .]
```

</details>

### PR DESCRIPTION
**Pull request by taconi**
## Description

Allow tasks to be documented with line breaks.

## Motivation behind this PR?

Closes #239.

## What type of change is this?

Bug Fix

## Checklist

- [X] `poe check` executed successfully.

## Issue

related #239

### CODE REVIEW

**Comment by nat-n** [comment]
Thanks for proposing this change. Looks OK as I explained on #239

What do you think about also making it strip whitespace from the help text around here? https://github.com/nat-n/poethepoet/blob/main/poethepoet/ui.py#L277C50-L277C63

**Comment by taconi** [comment]
Taking this opportunity, I would like to propose an adjustment for the
use of multiple lines. In the example, I had to space it in the help
itself to be aligned with the documentation. The idea is for the user
to be able to create their documentation without having to add
indentation

So with the following task:

``` toml
[tool.poe.tasks.lint]
cmd = "black --check --diff ."
help = "Run linting tools on the code base"

[tool.poe.tasks.fmt]
cmd = "black -S -l 79 $PATH"
help = """
Use "poe fmt" to format the code.

Examples:
  # Format all files
  poe fmt
"""
```

The result would already be aligned with the documentation of a single line:

``` shell
  lint                   Run linting tools on the code base
  fmt                    Use "poe fmt" to format the code.

                         Examples:
                           # Format all files
                           poe fmt
```

---

Regarding the stip, I would like to see if it would be possible to relocate the default because using strip it would be on the last line of the documentation.

Using that example task:

``` toml
[tool.poe.tasks.fmt]
cmd = "black -S -l 79 $PATH"
help = """
Use "poe fmt" to format the code.

Examples:
  # Format all files
  poe fmt
"""
[tool.poe.tasks.fmt.args.PATH]
options = ["-p", "--path"]
default = "."
help = """
Change the path that will be formatted.

Examples:
  # Formatting a specific path
  poe fmt -p tests
"""
```

The result with the strip in the help of this argument would be the following:

``` shell
	-p, --path           Change the path that will be formatted.

                         Examples:
                           # Formatting a specific path
                           poe fmt -p tests [default: .]
```

One idea would be to leave `[default .]` before the documentation:

``` shell
	-p, --path [default: .] Change the path that will be formatted.

                         Examples:
                           # Formatting a specific path
                           poe fmt -p tests
```

And maybe leave the help below:

``` shell
	-p, --path [default: .]
                         Change the path that will be formatted.
                         
                         Examples:
                           # Formatting a specific path
                           poe fmt -p tests
```


Do you think any of these changes make sense?

**Comment by nat-n** [comment]
Hey @taconi thanks for this ideas!

Yes I agree that indenting all lines by the amount required to match the column makes sense. As for repositioning the default. The logic that makes the most sense to me is to keep it at the end, but if help message is split over multiple lines then the default tag should be preceded by a line break so it appears on a new line. WDYT?

**Comment by taconi** [comment]
@nat-n Multi-line behavior applied.

The following task:

 ```toml
[tool.poe.tasks.fmt]
cmd = "black -S -l 79 $PATH"
help = """
Use "poe fmt" to format the code.

Examples:
  # Format all files
  poe fmt
"""
[tool.poe.tasks.fmt.args.PATH]
options = ["-p", "--path"]
default = "."
help = """
Change the path that will be formatted.

Examples:
  # Formatting a specific path
  poe fmt -p tests
"""
```

Produces the following help output:

 ```bash
Poe the Poet - A task runner that works well with poetry.
version 0.28.0

Result: No task specified.

Usage:
  poe [global options] task [task arguments]

Global options:
  -h, --help            Show this help page and exit
  --version             Print the version and exit
  -v, --verbose         Increase command output (repeatable)
  -q, --quiet           Decrease command output (repeatable)
  -d, --dry-run         Print the task contents but don't actually run it
  -C PATH, --directory PATH
                        Specify where to find the pyproject.toml
  -e EXECUTOR, --executor EXECUTOR
                        Override the default task executor
  --ansi                Force enable ANSI output
  --no-ansi             Force disable ANSI output

Configured tasks:
  fmt                   Use "poe fmt" to format the code.

                        Examples:
                          # Format all files
                          poe fmt
    -p, --path          Change the path that will be formatted.

                        Examples:
                          # Formatting a specific path
                          poe fmt -p tests
    [default: .]
```

**Comment by nat-n** [comment]
Thanks for the contribution @taconi :)

**Pull request merged**
