### PR TITLE
Skip PoetryExecutor if poetry is not found

### PR DESCRIPTION
**Pull request by kzrnm**
poe cannot run `PoetryExecutor` if poetry is set as an alias instead of `$PATH`.

I want to skip `PoetryExecutor` when poetry is not found.

### CODE REVIEW

**Review by nat-n — COMMENTED** [review]
Hi @kzrnm , I'm curious to know more about your use case for this? Though I guess this behaviour makes sense if you have a project with a poetry managed local venv, but just don't have poetry somewhere discoverable for whatever reason.

Though I think falling back to the simple executor could be surprising.

**Comment by kzrnm** [comment]
```powershell
# Microsoft.PowerShell_profile.ps1
Set-Alias poetry "${env:APPDATA}\pypoetry\venv\Scripts\poetry.exe"
```

I use poetry via alias on PowerShell, so that python interpreter cannot find poetry command and raise `FileNotFoundError` at PoetryExecutor.

https://github.com/nat-n/poethepoet/blob/903ed9af0dd313a6da32f24ec4357101435976d8/poethepoet/executor/poetry.py#L80-L85

## SimpleExecutor work properly.

In `poetry run`, poetry adds its venv directory to the `$PATH` of the subprocess.

### Example

```toml
[tool.poe.tasks.env]
shell = "/usr/bin/env | /usr/bin/grep ^PATH="
```

```
# Git bash
$ env PATH="" $APPDATA/pypoetry/venv/Scripts/poetry run poe env
Poe => /usr/bin/env | /usr/bin/grep ^PATH=
PATH=/mingw64/bin:/usr/bin:/c/Users/kzrnm/bin:/z/poethepoet/.venv/Scripts
```

**Comment by nat-n** [comment]
Thanks for the update. I'm happy to merge this once we work out what's going on with the tests.

Although maybe it could still be improved:

I wonder if it would be a good idea to log a warning when poe fallback to the SimpleExecutor in a poetry governed project because the poetry executable can't be found.

Alternatively I wonder if it would be better still if poe were to specifically check for poetry at `$APPDATA/pypoetry/venv/Scripts/poetry` if running on windows and poetry doesn't show up on the path?

**Review by nat-n — APPROVED** [review]

**Review by nat-n — APPROVED** [review]
Thanks for the update. I'm happy to merge this once we work out what's going on with the tests.

Although maybe it could still be improved:

I wonder if it would be a good idea to log a warning when poe fallback to the SimpleExecutor in a poetry governed project because the poetry executable can't be found.

Alternatively I wonder if it would be better still if poe were to specifically check for poetry at $APPDATA/pypoetry/venv/Scripts/poetry if running on windows and poetry doesn't show up on the path?

**Comment by kzrnm** [comment]
@nat-n I updated `fix/poetry` to the latest. 

i don't know why, but CI have worked.

**Pull request merged**
